/// <summary>
/// EncryptTemplates — build-time helper for DM.App.Licensing.EncryptedStrings
///
/// Usage:
///   dotnet run --project tools/EncryptTemplates -- --string "https://licenses.yourapp.com"
///   dotnet run --project tools/EncryptTemplates -- --key
///   dotnet run --project tools/EncryptTemplates -- --all
///   dotnet run --project tools/EncryptTemplates -- --encode-file path/to/plaintext.bin
///
/// Output is C# byte-array literals ready to paste into EncryptedStrings.cs.
///
/// The XOR key in this tool must match the key in EncryptedStrings.cs.
/// To rotate keys:
///   1. Run --key to generate a new random key
///   2. Update XorKey in both this file and EncryptedStrings.cs
///   3. Re-run --all to regenerate all ciphertext arrays
///   4. Paste the output into EncryptedStrings.cs
/// </summary>

using System.Security.Cryptography;
using System.Text;

// ── XOR key — must match EncryptedStrings.XorKey exactly ─────────────────────
// Change this BEFORE your release build; keep in sync with EncryptedStrings.cs
byte[] xorKey =
[
    0x7A, 0x3F, 0xC1, 0x82, 0xE4, 0x59, 0x0D, 0xB7,
    0x26, 0xFA, 0x91, 0x4E, 0x63, 0xD8, 0x15, 0xAC,
    0x70, 0x3B, 0xC9, 0x84, 0xE2, 0x57, 0x0B, 0xB5,
    0x24, 0xF8, 0x9F, 0x4C, 0x61, 0xD6, 0x13, 0xAA,
];

// ── Strings to encrypt ─────────────────────────────────────────────────────────
// Add your real values here, then run --all.
var strings = new Dictionary<string, string>
{
    ["ServerUrl"]  = "https://licenses.yourapp.com",
    ["DpapiSalt"]  = "SagarDM-v1-license-store-2025",
};

// ── CLI ───────────────────────────────────────────────────────────────────────

var args = Environment.GetCommandLineArgs()[1..];

if (args.Length == 0 || args[0] is "-h" or "--help")
{
    Console.WriteLine("""
        EncryptTemplates — generates XOR-obfuscated string constants for EncryptedStrings.cs

        Usage:
          --key              Generate a new random 32-byte XOR key and print it
          --string <text>    Encrypt a single string and print the byte array
          --all              Encrypt all strings defined in the source and print C# code
          --verify           Decrypt all stored ciphertexts and verify they round-trip
          --help             Show this message
        """);
    return;
}

switch (args[0])
{
    case "--key":
        GenerateKey();
        break;

    case "--string":
        if (args.Length < 2) { Console.Error.WriteLine("Usage: --string <text>"); break; }
        PrintEncrypted("_custom", args[1]);
        break;

    case "--all":
        Console.WriteLine("// ── Auto-generated by tools/EncryptTemplates --all ──────────────────");
        Console.WriteLine("// Paste into DM.App/Licensing/EncryptedStrings.cs");
        Console.WriteLine("// Verify the XorKey in this file matches EncryptedStrings.XorKey.");
        Console.WriteLine();
        foreach (var kv in strings)
            PrintEncrypted($"_{char.ToLower(kv.Key[0])}{kv.Key[1..]}", kv.Value);
        break;

    case "--verify":
        VerifyRoundTrip();
        break;

    default:
        Console.Error.WriteLine($"Unknown option: {args[0]}.  Run --help for usage.");
        Environment.Exit(1);
        break;
}

// ── Implementation ────────────────────────────────────────────────────────────

void GenerateKey()
{
    var key = RandomNumberGenerator.GetBytes(32);
    Console.WriteLine("// Replace XorKey in BOTH EncryptedStrings.cs AND tools/EncryptTemplates/Program.cs");
    Console.WriteLine("private static ReadOnlySpan<byte> XorKey => new byte[]");
    Console.WriteLine("{");
    for (int i = 0; i < key.Length; i++)
    {
        if (i % 8 == 0) Console.Write("    ");
        Console.Write($"0x{key[i]:X2}");
        if (i < key.Length - 1) Console.Write(", ");
        if ((i + 1) % 8 == 0 || i == key.Length - 1) Console.WriteLine();
    }
    Console.WriteLine("};");
}

void PrintEncrypted(string fieldName, string plaintext)
{
    var src     = Encoding.UTF8.GetBytes(plaintext);
    var cipher  = Xor(src);

    // Print the round-trip to stderr so you can verify
    Console.Error.WriteLine($"  {plaintext,-60} → {plaintext.Length} bytes");

    Console.WriteLine($"// Encrypts: \"{plaintext}\"");
    Console.WriteLine($"private static readonly byte[] {fieldName}Ct = [");
    Console.Write("    ");
    for (int i = 0; i < cipher.Length; i++)
    {
        Console.Write($"0x{cipher[i]:X2}");
        if (i < cipher.Length - 1)
        {
            Console.Write(", ");
            if ((i + 1) % 12 == 0) { Console.WriteLine(); Console.Write("    "); }
        }
    }
    Console.WriteLine();
    Console.WriteLine("];");
    Console.WriteLine();
}

void VerifyRoundTrip()
{
    Console.WriteLine("Round-trip verification:");
    bool allOk = true;
    foreach (var kv in strings)
    {
        var enc = Xor(Encoding.UTF8.GetBytes(kv.Value));
        var dec = Encoding.UTF8.GetString(Xor(enc));
        bool ok = dec == kv.Value;
        Console.WriteLine($"  {kv.Key}: {(ok ? "OK" : "FAIL")} — \"{dec}\"");
        if (!ok) allOk = false;
    }
    Console.WriteLine(allOk ? "\nAll OK." : "\nFAILURES detected — check XorKey sync.");
    if (!allOk) Environment.Exit(1);
}

byte[] Xor(byte[] src)
{
    var result = new byte[src.Length];
    for (int i = 0; i < src.Length; i++)
        result[i] = (byte)(src[i] ^ xorKey[i % xorKey.Length] ^ (byte)(i * 0x5D));
    return result;
}
